# Generated by Django 3.0.8 on 2021-02-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querybook', '0002_solution_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='prism_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
