# Generated by Django 3.0.8 on 2021-02-26 06:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querybook', '0003_query_prism_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_form',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
