# Generated by Django 3.0.8 on 2021-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querybook', '0004_auto_20210226_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='keyword',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
