# Generated by Django 3.0.8 on 2021-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_title',
            name='keyword',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
