# Generated by Django 3.0.8 on 2023-07-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_title_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='program_title',
            options={'ordering': ['id']},
        ),
    ]
